### ISSUE TITLE
Drink Collections

### ISSUE THREAD

**Issue by raddacle** [karlomikus/vue-salt-rim#102]
I see that Bar Assistant has the capability to create and use collections, though I can't find a method to set a collection in SaltRim. Where can I find that?

**Comment by zhdenny** [comment]
Bar Assistant and SaltRim are two different projects with two different releases.

Typically new features get added to the server-side of things first (Bar Assistant) then later get added to the client-side later (SaltRim). You can see everything by looking at the changes/updates for the latest release of each project.

tldr; not yet in SaltRim

**Comment by raddacle** [comment]
Ah okay. I'm working on using Bar Assistant api to autogenerate a sleek menu, with the idea of having Salt Rim as backend gui for the bartender, and using the collections method would make a lot more sense than tags. I'll wait patiently for collections to be integrated.

The end result would resemble something like a menu created by u/LoganJFisher
https://www.overleaf.com/project/64bbc4a569763250557cc2d3

**Comment by zhdenny** [comment]
I'd love to see what you are talking about but......I get permission errors when I visit that website

![Screenshot_20230722-170716](https://github.com/karlomikus/vue-salt-rim/assets/26662131/3ba82621-cac9-43ba-982b-3505ff91db3e)

**Comment by raddacle** [comment]
Sorry about that; wrong link. https://www.overleaf.com/project/5f120402b5e50e0001cc4e1c

**Comment by zhdenny** [comment]
The overleaf link still has weird permission issues.

But I'm able to get to it from the reddit post successfully. Cool! Thanks

**Comment by karlomikus** [comment]
Collections are currently being implemented in salt rim, you can check develop branch or dev docker image if you want to see the progress.
