### ISSUE TITLE
Creating an API Key

### ISSUE THREAD

**Issue by raddacle** [karlomikus/vue-salt-rim#103]
I'm trying to figure out the syntax for the api. The built doc is very useful, though I can't find any documentation on how authorization is handled. Based on the dev env, it seems its defined under APP_KEY so I entered a alphanumeric string of 32 characters, but I haven't been able to get a successful response with that key. I monitored SaltRim network traffic and found the key it uses, which works, though I do not know if this is the intended approach or if it will expire eventually.

**Comment by karlomikus** [comment]
When you login with the credentials, you will get a token that you can send with the requests.
