### ISSUE TITLE
Improve Import Cocktail Ingredient Selection

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#110]
Currently, the Import feature will provide a preview of what will be parsed including the ingredients, proportions, etc.

The ingredient names are pulled directly from the import source. Often these ingredient names are slightly different than what I already have in my ingredient database. I would like to avoid duplicate ingredients being created upon import.
For example, "Amontillado Sherry" versus "Sherry - Amontillado".

In the import preview (see screenshot), The user can edit the ingredient name before the actual import. This helps avoid creating a duplicate ingredient. I want this to be better/easier. It would be AWESOME if the ingredient fields were searchable against your ingredient database. It would make imports from Websites so much easier to adapt source ingredients into user database ingredients which already exist. Does that make sense?

![Screenshot_20230906-141632](https://github.com/karlomikus/vue-salt-rim/assets/26662131/887f0d30-69ee-4cfe-bf5a-9d6baed523e2)

**Comment by karlomikus** [comment]
I'm aware of the annoyance of trying to match ingredients :) . I do have some plans to add button that will try to preview and match ingredients before adding new one

**Comment by zhdenny** [comment]
Yay! You're awesome

**Comment by karlomikus** [comment]
Added manual match on import screen in v2
