### ISSUE TITLE
Searching on Cocktail/Ingredient pages doesn't reset page navigation

### ISSUE THREAD

**Issue by TheSpoon98** [karlomikus/vue-salt-rim#111]
When using the search on cocktail or ingredient pages, if you've navigated to another page, say 3/7, using the search on the page keeps you on page 3 even if it doesn't exist for that search.  Example (navigated to page 4, search for Dry Martini):
![image](https://github.com/karlomikus/vue-salt-rim/assets/14792646/03aea213-1662-4293-a76d-4a423af630a2)

Also - when using the "Clear All Filters" button, while it clears the contents of the search - the listing of contents doesn't revert to a "clean" search. Example (continued from prior, just clicked "Clear all filters" button:
![image](https://github.com/karlomikus/vue-salt-rim/assets/14792646/2f6534ef-5f97-4a25-859a-12d9550c3788)

**Comment by karlomikus** [comment]
Fixed, thanks!
