### ISSUE TITLE
[Feature Request] Admin role cannot see ALL BARS

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#128]
To Reproduce:

1. A General User Role creates their own bar.
2. An Admin User Role (Zach) cannot see or manage the Bar created by the General User Role.....

Screenshot below only shows a Single Bar.....created by the Admin. But the Admin cannot see or manage the bar the General User Role created. I feel like the Admin should be able to Manage and See All Bars on the BarAssistant Database from this page.

![image](https://github.com/karlomikus/vue-salt-rim/assets/26662131/6ea03d9a-c7aa-44a4-9ce6-004ce4124ccc)

**Comment by karlomikus** [comment]
I think there is a general misunderstanding about roles. User roles are tied to a bar that user is a member of. If a user creates an account (or you create a user) on your instance he can create his own bar and do what he wants with it.

There is a ENV variable `MAX_USER_BARS=50` which if you set to `0` will disable creating new bars.

**Comment by zhdenny** [comment]
So then is there no account which is considered the Admin of the entire BarAssistant instance? Can there be such an account?

**Comment by karlomikus** [comment]
There is no account like that planned.
If you have access to your server, you have the access to the database. If you really need to know what's going on, you could use some database management to connect to DB and do some management directly from there.
