### ISSUE TITLE
User not getting deleted in Database

### ISSUE THREAD

**Issue by h3g0rt** [karlomikus/vue-salt-rim#132]
If you delete a User, it is no longer showing up in SaltRim but it is not deleted in the users table in the DB. You can still login with the deleted credentials and you cannot create another account with the Email of the deleted account because it still exists in the Table.

**Comment by karlomikus** [comment]
Currently when you delete a user, you delete his bar memebership. If you want to delete a user, he needs to login and go to his profile and delete his account from there.

You will be able to toggle this behavior in next minor version via ENV variable.

**Comment by karlomikus** [comment]
New options added in [v3.2.0](https://github.com/karlomikus/bar-assistant/releases/tag/v3.2.0)
