### ISSUE TITLE
ABV not getting updated when importing Database.

### ISSUE THREAD

**Issue by h3g0rt** [karlomikus/vue-salt-rim#133]
I recently upgraded to 3.x and had problems with the migration. There were some errors so I exported the DB and imported to a new, clean instance. It went fine, apart from loosing Users etc. but that was to be expected. Unfortunately the ABV is not getting calculated for the imported Cocktails, it does not show up until I edit a cocktail and save it again.

**Comment by karlomikus** [comment]
When you say that you exported the DB, do you mean from the previous version? You can't use v2 zip file for the v3.

If you have v2 zip file, maybe try downgrading to latest v2, then import the data, check if everything is there, then upgrade to v3.
