### ISSUE TITLE
Cocktail editor: Improve tag selection

### ISSUE THREAD

**Issue by frank42hh** [karlomikus/vue-salt-rim#134]
HI,

the tag selection box does not behave as expected. When creating or editing a cocktail, the input box does present a list of present tags to select, but after selecting the first tag, it's impossible to select a second one, and when manually typing away, the missing autocomplete makes it hard to match existing tags which leads to multiple instances of the same meaning (like Classic, Classics and classics).

I would therefore suggest to
a) make this input field select() only as already used for the "Utensils" section (preferred) or type input with autocomplete, making it more convenient to add one or multiple tags from dropdown list and prevent adding similar tags due to misspelling
b) when using type input: make case insensitive comparison to prevent adding duplicates due to mixed uppercase and lowercase 
c) optionally restrict creation of new tags in the "tags" setting tab only

However, one word of appreciation has to be spoken out: I really enjoy this project, the application works fine, fast and is quite shiny. It's so good that we decided to use it as our main source of cocktail recipes at a nice little cocktail bar in Hamburg, Germany

**Comment by karlomikus** [comment]
Tag selection is currently a native [datalist element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist), so it's not too advanced. I definitely need to implement case insensitive matching.
I also need to explore some multi-select components/plugins that available.

**Comment by frank42hh** [comment]
I see. In that case I think the easiest solution would be to switch to a [multiple select element(https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple)
