### ISSUE TITLE
Improve cocktail preview on ingredient page

### ISSUE THREAD

**Issue by daniel-simpson** [karlomikus/vue-salt-rim#138]
As per the title, would love to (optionally?) see a list of cocktail previews (like you get on search page) from the ingredient screen, that show all the cocktails you can make with that ingredient.

Happy to work on it too, if it's deemed useful.

**Comment by karlomikus** [comment]
I like it, it should probably use the smaller cocktail card like in the shelf page. The issue I see is that some ingredients like lemon juice/gin/whiskey can have a lot of related cocktails and that could overwhelm the ingredient page.
