### ISSUE TITLE
Resize cocktail image to fit page when "Generate recipe image"

### ISSUE THREAD

**Issue by RandomLettersAndNumb3rs** [karlomikus/vue-salt-rim#140]
It appears as though many pictures are too large to fit in the generated recipe image, leaving a blank space.

**Comment by karlomikus** [comment]
Hello,
Can you send an example of such image?

**Comment by karlomikus** [comment]
This looks like an issue with image loading. There were some updates related to images recently.

Trying clearing your site cache.
Also, does the picture show when you create a public link, and visit it. For example: https://bar.karlomikus.com/e/cocktail/01HCAEG2TWSEVPJHXMHJBMSWRJ/airmail-1

**Comment by karlomikus** [comment]
That's weird, I'll do some digging.

Is there any error in the console/network?

**Comment by karlomikus** [comment]
CORS issue, will be fixes in next release
