### ISSUE TITLE
No image on image share

### ISSUE THREAD

**Issue by beasthouse-au** [karlomikus/vue-salt-rim#157]
I am trying to generate a recipe image via the share function and whenever I do so, the image of the cocktail itself does not render in the image. This predominantly happens using iOS across multiple browsers (Safari, FireFox, Chrome). I've also had issues with it using Safari on MacOS, however Firefox works fine on MacOS.

![image](https://github.com/karlomikus/vue-salt-rim/assets/78465928/9b902779-e516-4425-aa87-0dc0dc803794)

![image](https://github.com/karlomikus/vue-salt-rim/assets/78465928/d9d179e5-f79d-4249-b373-832b676518eb)

**Comment by karlomikus** [comment]
Hello,
can you check Network tab in the console for errors. This seems to happen when there is an issue with cors.
