### ISSUE TITLE
Default admin login

### ISSUE THREAD

**Issue by bamfcoco** [karlomikus/vue-salt-rim#164]
Im trying to get logged in with the default admin account. From what i can tell it should be admin@example.com - passord

When trying this i get user doesnt exist. If I try to register said account it creates a non admin account.

Are the default credentials something different?

**Comment by bamfcoco** [comment]
You can disregard. I didnt let bar assistant fully setup. Didnt realize I needed to give it a bit.

**Comment by karlomikus** [comment]
Since version 3 we don't include default user anymore.
Glad you got it solved
