### ISSUE TITLE
Placing child ingredient on shelf doesn't mark cocktail with parent ingredient as makeable unless I also add the parent ingredient to my shelf.

### ISSUE THREAD

**Issue by rwedmonds** [karlomikus/vue-salt-rim#166]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
For example, I add Papa's Pilar Dark Rum to my ingredient list and specify "Dark Rum" as a parent ingredient. I then add Papa's to my shelf. My expectation is that any cocktail that requires Dark Rum would show up as a Cocktail I Can Make since I do indeed have Dark Rum. However, this only happens when I add Dark Rum to my shelf.

**To Reproduce**
As far as I can tell this is the default behavior.

**Versions:**
 - Docker: 24.0.5, build 24.0.5-0ubuntu1~22.0.4.1
 - Chrome

**Additional context, log outputs...**
Parent ingredient doesn't seem to have a clear link to child ingredients.

**Comment by karlomikus** [comment]
Ingredient shelf status is not better represented
