### ISSUE TITLE
Configuration for Meilisearch when API Key is required appears to be missing from documentation

### ISSUE THREAD

**Issue by proffalken** [karlomikus/vue-salt-rim#170]
When setting up the Bar Assistant server there is a configuration flag for connecting to Meiliesearch using the MASTER_KEY as an API Token.

At the moment, I am seeing the following in the Meilesearch logs when trying to add a cocktail to a menu:

```
[2024-05-05T18:27:10Z DEBUG actix_web::middleware::logger] Error in response: ResponseError { code: 403, message: "The provided API key is invalid.", error_code: "invalid_api_key", error_type: "auth", error_link: "https://docs.meilisearch.com/errors#invalid_api_key" }
```

The browser returns a 403 error, unless logging in Meilesearch is set to something other than DEBUG, at which point it returns a basic 400 error (See https://github.com/karlomikus/bar-assistant/issues/278 ).

[This code](https://github.com/karlomikus/vue-salt-rim/blob/3c36d563507848ffa462cc7897d4cfc77cb5e39c/src/components/SiteAutocomplete.vue#L70) appears to suggest that I should be able to set the `search_driver_api_key` somehow, but I can't see anything in the code that will enable me to do that.

Is there an environment variable I'm missing here to get me authenticated to Meilesearch from the front-end?

**Comment by karlomikus** [comment]
You get the api key via Bar Assistant server endpoint `GET /bars/{id}`, you'll need to check your BarAssistant<>Meilisearch config.

You can also try to logout, then login back in, go to bars, and select a new bar.

**Comment by proffalken** [comment]
@karlomikus - thanks, that set me on the right path.

I'd had a few attempts at getting this running and it turned out that the issue was stale data in Bar Assistant API Server for the API Keys in Meilesearch.

I tore down the entire stack, deleted all the storage, and recreated everything and it now works perfectly well - thanks for such a great platform!
