### ISSUE TITLE
Create new Username/Password

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#18]
Maybe I'm missing something...but I do not see any method to create or modify a username/password.

The only thing that works is admin@example.com  //  password.

This is the only thing stopping me from actually starting to use this and begin adding all my cocktails into it

**Comment by karlomikus** [comment]
Hi, you are not missing anything :D

Register and profile editing will be in next version (v0.5), planned to be released by the end of this week, along with BA version 1.0.1
