### ISSUE TITLE
Clipboard not receiving data from share menu

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/vue-salt-rim#184]
It looks like the [clipboard error](https://github.com/karlomikus/vue-salt-rim/issues/127) has come back. I have a fresh install and cannot get any of the "Copy as ..." or the cocktail public link popup's "Copy link" buttons to copy to my clipboard.

**Comment by zhdenny** [comment]
Copy to clipboard (in all of its forms) works flawless for me....

**Comment by zeekaran** [comment]
It doesn't work on my install. I've seen it work on the frontend demo. I have tried on Chrome and Firefox, across Windows and Debian. Checking the network debug window, it doesn't look like anything is wrong. Not sure what to look for in my docker logs.

**Comment by karlomikus** [comment]
Do you have HTTPS enabled. Copy is using [navigator.clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard), and it needs secure context.

**Comment by zeekaran** [comment]
That was it! Phew.
