### ISSUE TITLE
Option to hide prices from menu

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/vue-salt-rim#186]
The menu feature should have an option to hide prices. I could be wrong, but I think most users here are amateur / home bartenders. Just a simple checkbox, would suffice (per drink or for the whole menu). Alternatively, "0.00" or "null"/empty string (which is currently not allowed and defaults to 0.00) could just not display.

**Comment by reefland** [comment]
oops. I made a duplicate of this <https://github.com/karlomikus/bar-assistant/issues/308>

**Comment by karlomikus** [comment]
Live in [v2.17.0](https://github.com/karlomikus/vue-salt-rim/releases/tag/v2.17.0)

**Comment by reefland** [comment]
Looks good, thanks!
