### ISSUE TITLE
Implement PWA

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#19]
This is a feature request for Web App Capabilities.

This looks very good on Mobile but Web App Capabilities would make this even more convenient/smooth looking for Mobile users.

**Comment by karlomikus** [comment]
Hi,

Do you mean [PWA support](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)?

If yes, I have a plan to support this, but probably not for the stable release.

**Comment by zhdenny** [comment]
Correct, PWA support

So glad to hear you already have plans for this. Yay!
