### ISSUE TITLE
Remove Registration Button.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#190]
I have `ALLOW_REGISTRATION=false` and both Bar Assistant and Salt Rim see it:
```
root@bar-assistant-salt-rim-7bdcb8bbcb-rwlln:/# env | grep ALLOW 
ALLOW_REGISTRATION=false
```
```
root@bar-assistant-5667fff5b9-d7dvc:/var/www/cocktails# env | grep ALLOW
ALLOW_REGISTRATION=false
```

It does appear that the registration does not actually work, but the `[Register]` button still renders and I still get the Registration Dialog box.

At least upon clicking `[Register]` it fails with a `NOT FOUND` randomly at the top of the screen.

![image](https://github.com/user-attachments/assets/317e8d93-6957-424b-9eb8-ef3c9b09654c)

Is this expected? It seems like the `[Register]` button and this screen shouldn't even render when set to `false`.  Cleared cache, etc.

**Comment by karlomikus** [comment]
Introduced `ALLOW_REGISTRATION` env var for salt rim in [v2.17.0](https://github.com/karlomikus/vue-salt-rim/releases/tag/v2.17.0)
