### ISSUE TITLE
Reduced ability on Guest user.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#196]
The Guest user description says `Can view, rate and favorite cocktails` which sounds perfect. However, they can actually do more than I think a guest should do. Perhaps a new role "Guest Limited" or current "Guest" role should be renamed "User" and new actual "Guest" role created.

I found #81 which was dismissed to quickly.  The current "Guest" is really more of a "User" and not a "Guest".  Ideally a guest:
* Cannot create collections (but perhaps can view shared ones)
* Cannot manage a shelf (should not even see anything related to shelf)
* Should not see how many cocktails they can make, a guest user is not making cocktails.
* Should not have a shopping list or ability to add to them.

The [Bar Assistant API docs](https://docs.barassistant.app/#user-roles) description of guest role does not say a guest should be doing these things:

![image](https://github.com/user-attachments/assets/24153f41-9bf2-498b-a4c7-3718557fdaa1)

**Comment by karlomikus** [comment]
Hello,
Guest is just a user with permissions that don't really have effect on anything in the actual bar. So everything he does (like collections, personal shopping list, shelf) is "viewable" only to him.

**Comment by reefland** [comment]
I understand what you are saying.  I think my issue is that what is documented on what the "Guest" role is supposed to do and what the guest can actually do in Salt Rim do not line up.  A guest user can do a lot more than is documented.
