### ISSUE TITLE
Remove link to login screen from Menu.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#197]
When viewing a Menu the Bar Assistant logo is a clickable link that takes them to the login screen:

![image](https://github.com/user-attachments/assets/c6d77d50-1eda-4097-b48e-d3210508add3)

Please remove the link ability, customers viewing menu shared by QR code should not have direct link to a login page.

**Comment by karlomikus** [comment]
Live in [v2.17.0](https://github.com/karlomikus/vue-salt-rim/releases/tag/v2.17.0)
