### ISSUE TITLE
Cannot enter 1/8oz or 3/4 tsp

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/vue-salt-rim#199]
Seems I cannot enter anything less than 1 teaspoon, nor an amount less than 1/4oz. I first tried manually entering in 1/8th oz but it would just show as 1/4oz after clicking save. I tried entering 3/4 tsp and it renders 0.75 tsp but will not let me save.

![image](https://github.com/user-attachments/assets/74e8b9c0-1d34-4a57-a300-04044c711e9c)

**Comment by reefland** [comment]
When I enter `1/8 oz` I see it shows as `1/4 oz` however after saving it, when I go to edit the ingredient again the value shown is `0.125` which is the correct amount for `1/8 oz` even if `1/4` is shown.   It seems to save correctly, just shown incorrectly.

When I try to use `3/4 teaspoon` or `3/4 tablespoon` I get:
![image](https://github.com/user-attachments/assets/cee7d5c6-f566-42e9-92c7-020f4bd69474)

Related to this issue, I created an ingredient for `cinnamon stick` and tried to use a unit such as `1/2 stick` and that doesn't work either.  For now I've been using `0 ounce` and put the correction in the comment.

Salt-Rim doesn't seem to expose what are valid units of measure.  A table of units / conversion table would be handy in settings. I also reviewed the API docs don't see a way to query units.

**Comment by karlomikus** [comment]
Hello,
from API point of view, there is no table of conversion. Amount needs to be number/float and unit can be any string. What salt-rim does is try to convert units to float, and this worked but only for `oz` units.

This behavior should be fixed/improved with [v2.17.0](https://github.com/karlomikus/vue-salt-rim/releases/tag/v2.17.0). If you can, try it on this version and let me know if it's fixed.

**Comment by zeekaran** [comment]
![image](https://github.com/user-attachments/assets/039f8ba8-e5bd-4205-9e4d-db64d41fc88e)

Saving 1/8 oz, it then displays as 0.125 in the editor window, but the recipe is still displaying 1/4.

**Comment by karlomikus** [comment]
I pushed a bugfix in a new version so check if it improved

**Comment by zeekaran** [comment]
Close enough!

![image](https://github.com/user-attachments/assets/4587fe73-293e-466e-b1da-027f0abb0f84)
