### ISSUE TITLE
Substituted ingredients needs "and" option.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#204]
The substituted ingredients seems to assume multiple selections is an "or":

![image](https://github.com/user-attachments/assets/532e87ea-79a4-4122-86ed-f42949731e24)

I need the combination of 2 ingredients to make a substitute.  Perhaps a radio button to select between `or` and `and`?

![image](https://github.com/user-attachments/assets/21b3fed5-d180-4c29-80d6-43b5d97be39f)

**Comment by zhdenny** [comment]
That seems like a pretty specific distinction....

Maybe it's easier to just use the Note features on an ingredient or on the cocktail itself to say this sorta thing.

Sounds like a neat feature though.

**Comment by reefland** [comment]
Yes, I'm using comments and notes on other ingredients for now to make it clear. I agree, it's a handy feature.

Another example I can think of -- Tiki drinks that specifically call for `Donn's Mix` which might be premade on-hand, but I'd like to shows that grapefruit juice and cinnamon syrup can be used as a substitute.

**Comment by karlomikus** [comment]
The way substitutes now work, this will not change.
What I can recommend as a workaround, create a new complex ingredient that is made of other ingredients. So for example, create Donn's Mix and add grapefruit juice and cinnamon syrup as ingredient parts.

![Snimka zaslona 2024-08-07 214527](https://github.com/user-attachments/assets/ce004343-41c6-4020-8716-ff5c5d5b8ba2)

**Comment by reefland** [comment]
For me with the substitutes allowing amount/units to be set works better than just a complex ingredient.
