### ISSUE TITLE
"Share collection with all bar members" checkbox not working

### ISSUE THREAD

**Issue by zeekaran** [karlomikus/vue-salt-rim#206]
I created a collection and checked the box:

![image](https://github.com/user-attachments/assets/eb1754ec-1517-4e31-bec4-56a9df6b3438)

Then I logged into a guest account on my bar and it is not visible.

![image](https://github.com/user-attachments/assets/fd231689-16ce-4c87-8ff4-f0ae3b0fff36)

This happens regardless of the order. I created a collection, created a guest user, no collection shared. Then I created a new collection and shared it, still no collections for the guest.

**Comment by karlomikus** [comment]
When shared, collections currently only show under "Collections" filter on cocktails main page.

**Comment by zeekaran** [comment]
Huh, so they do. Is that intentional?

**Comment by karlomikus** [comment]
Yes, shared collections can only be viewed by other bar members.

**Comment by zeekaran** [comment]
What's the purpose of not having the collection from the admin be added to a guest account's collection page? Why the separation?

**Comment by karlomikus** [comment]
Because guests can't edit collection that are not theirs.
Is there anything specific you are trying to solve?

**Comment by zeekaran** [comment]
As long as the design intent of the collections page is to just be a fancy filter button to go back to the cocktails page, no I guess not.

I'm still in the Plex/Jellyfin mindset where collections are a separate view, and my users are just viewers with no intent to make their own collections.
