### ISSUE TITLE
Substitutes ingredient(s) shows a number from URL [cosmetic issue]

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#209]
Not sure if this is new, or I just noticed, but substitutes show a number at the end:
![image](https://github.com/user-attachments/assets/6ef7d43e-a7d7-4af6-b2a7-03bf8e132431)

That `1` is part of that ingredient URI such as `/ingredients/lime-juice-1`.

Please strip off the number from the end when showing the Substitute(s).

**Comment by karlomikus** [comment]
Thanks for report!
