### ISSUE TITLE
Using "Duplicate and Edit" to create new cocktail, is not a "new" cocktail.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#213]
When using the `Duplicate and Edit` feature, the new cocktail seems to inherit the creation timestamp of the old cocktail it was based on.  Thus it does not show up in Shelf  under "Latest cocktails".  

I'd like the new cocktail to have the current timestamp as the creation date instead.

**Comment by reefland** [comment]
I tried again 2 other times, and it worked as expected.  Not sure what happened the 1st time.  I duplicated a Hot Toddy to make a variant and the new one has the date of the original (my install date).  I tried again 2 times, to make more variants of the original and they each have today's date as expected.

**Comment by karlomikus** [comment]
Vue components tend to have some issues with some child components not updating state when switching between routes. I'll recheck the `Date` components, it's possible that they have similar issues.
