### ISSUE TITLE
Create Ingredient Categories

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#22]
It would be nice to be able to create ingredient categories.

Useful Examples:

1. Amaro is a rather large category of liqueur a user might want to create if they own many different Amaro
2. A user has 30 different Jamaican Rums. It would be a good if the user could create a Jamaican Rum category.

**Comment by karlomikus** [comment]
Yeah, this is missing currently in web app (alongside glass types). It will be added in the stable release.

In the meantime you can manually create and edit categories through API calls.

**Comment by karlomikus** [comment]
Implemented in new settings page in v0.6.0.

Thanks!
