### ISSUE TITLE
After upgrading to version 4, editing an ingredient results in the form not loading

### ISSUE THREAD

**Issue by penguincrest** [karlomikus/vue-salt-rim#225]
After upgrading to Salt Rim 3 and Bar Assistant 4, if I go to edit an ingredient I don't get a loading screen, its just the header/top menu and footer with no form or other content.  The UI doesn't seem to recover until I fully refresh the page, once I get the blank page any other menu item I click on does not show any content.

**Comment by zhdenny** [comment]
Be sure you delete cache/history. Or try on a Totally different browser which hasn't been used to access SaltRim before. I think this is a cache issue.
