### ISSUE TITLE
More text support in Cocktail/Ingredient Description Fields

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#23]
The "Description" field seems to be a good/only place to add additional information/notes about an ingredient or cocktail. For example, a user may add a slight variation in the primary spec of a cocktail or tasting notes for a Spirit in this Description field.

At a minimum, It would be nice to allow for insertion of a new line in this field. It would make these additional notes read easier. Or maybe allowing Markdown text support in this field would help.

In this screenshot, I have tasting notes at the end of the description. A new line separating the description from the tasting notes would look nice. I also attempted to BOLD the information using markdown.

![image](https://user-images.githubusercontent.com/26662131/206231236-7b99cdde-51cd-4278-adf0-c057653687bd.png)

**Comment by karlomikus** [comment]
Markdown for ingredient description is enabled in v0.6.0

Thanks!
