### ISSUE TITLE
Default Measurement Units

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#24]
While viewing a cocktail, three different units of measurement are provided for the spec. Salt Rim always defaults to "ml". Can there be a way to configure what the default unit of measurement is? Or possibly a way for Salt Rim to remember your measurement unit selection. I would like to view Cocktail specifications in "oz"

**Comment by karlomikus** [comment]
In v0.6.0, selected measurement unit will be remembered.

Thanks!
