### ISSUE TITLE
Recipe JSON Import Problems

### ISSUE THREAD

**Issue by sweisgerber** [karlomikus/vue-salt-rim#244]
Hi there,

I got a question or bug report, depending on the outcome :)

When importing Recipes in JSON format via the web-interface `https://SITE/cocktails/scrape` it doesn't work and no hint is shown in the UI why or even that it failed. It just happens nothing.

The JSON I post is in schema.org/Recipe format.
To have valid data, I exported the included recipes and tried importing a 1934 cosmo clone and had still no luck

```json
{
    "@context": "https://schema.org",
    "@type": "Recipe",
    "author": {
        "@type": "Organization",
        "name": "Recipe exported from Bar Assistant"
    },
    "name": "1934 Cosmo CLONE",
    "datePublished": "2024-08-28",
    "description": "A simple sour can be so different with the right base spirit. The 1934 Cosmo hits its stride with a complex and floral gin. Grab a bottle whose botanicals include multiple berries and flowers. We&#039;d suggest Monkey 47.",
    "image": {
        "@type": "ImageObject",
        "author": "LiberAndCo | Caer Maiko Ferguson",
        "url": "https://bar.dystopianfuture.org/bar/uploads/cocktails/1/1934-cosmo-1_kRvRKi.jpg"
    },
    "recipeInstructions": "1. Add all ingredients to a cocktail shaker\n2. Add ice and shake hard for 20 seconds\n3. Strain into a chilled coupe\n4. Garnish with an orange twist",
    "cookingMethod": "Shake",
    "recipeYield": "1 drink",
    "recipeCategory": "Drink",
    "recipeCuisine": "Cocktail",
    "keywords": "Spring, Fruity",
    "recipeIngredient": [
        "60 ml Gin",
        "15 ml Lemon juice",
        "15 ml Raspberry Syrup"
    ]
}
```

Checking the Console brought some insights:

```
Unable to parse JSON TypeError: i.ingredients is undefined
    A https://bar.dystopianfuture.org/assets/CocktailsScrapeView-DX8CG6d2.js:1
    D https://bar.dystopianfuture.org/assets/CocktailsScrapeView-DX8CG6d2.js:1
    r https://bar.dystopianfuture.org/assets/index-Dd9whwMf.js:19
    Ni https://bar.dystopianfuture.org/assets/index-Dd9whwMf.js:14
    cn https://bar.dystopianfuture.org/assets/index-Dd9whwMf.js:14
    n https://bar.dystopianfuture.org/assets/index-Dd9whwMf.js:19
CocktailsScrapeView-DX8CG6d2.js:1:5689

```
and when I switched `recipeIngredient` to `ingredients` I got the next form, where one can modify the imported recipe (but only description and name being filled out, ingredients and the rest where blank).

Am I right, that I would have to submit a json that is compatible with the format at: https://api.barassistant.app/docs#/operations/f46bb44c14109f5d529b854e81d57150,
specifically putting the response body format in `source` when submitting https://api.barassistant.app/docs#/operations/f46bb44c14109f5d529b854e81d57150#response-body?

Perhaps you want to include some hints on the proper format, error reportig or even make it schema.org recipe compatible?

Anyway, you have a great product that I like a lot.

Many Regards

Sebastian

**Comment by karlomikus** [comment]
Hello, 
Docs are definitely missing more information, I'll update them.

Endpoint `/api/import/cocktail` source body currently only supports recipes that are in [draft2](https://barassistant.app/cocktail-02.schema.json) or [draft1](https://barassistant.app/cocktail-01.schema.json) JSON schema.

Scrape endpoint takes any URL, tries to extract recipe and converts it into json structure conforming to draft 2 schema.
