### ISSUE TITLE
Feat: avoid on mobile avoid screen to go black on cocktail recipe page

### ISSUE THREAD

**Issue by daschy** [karlomikus/vue-salt-rim#256]
When I am making a cocktail and I am reading the recipe from my phone's browser, after a few seconds the phone dims the screen and it goes black. I need to touch the screen (often with dirty fingers) in the middle of the recipe preparation.

Ideally it would be useful to have something like the toggle "Cook Mode" in the link below https://www.foodandwine.com/recipes/tom-collins

Thanks!

PS: awesome app btw

**Comment by karlomikus** [comment]
Hello,

There should be "Prevent screen locking" checkbox under "Instructions" when you click on a cocktail. That should do exactly what you want.

**Comment by daschy** [comment]
Hi, 

I used dockers' dev and 3.4.1 versions, but I cannot see that checkbox. Is there any settings to update?

![CleanShot 2024-11-22 at 16 52 11](https://github.com/user-attachments/assets/c3a11910-b355-4406-bc4b-11234f24a346)

![CleanShot 2024-11-22 at 16 53 14@2x](https://github.com/user-attachments/assets/14eec9db-709b-49c1-84fd-1659d3785d19)

**Comment by karlomikus** [comment]
Make sure that you are running the client via https, it's required for this [feature to work](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API).

**Comment by daschy** [comment]
Done. I added ssl to nginx and I see the checkbox

Thanks
