### ISSUE TITLE
Adding cocktail to menu gives meili 404

### ISSUE THREAD

**Issue by gamegoofs2** [karlomikus/vue-salt-rim#258]
When I go to add a cocktail to the menu I just get a bar saying Cocktails.
![image](https://github.com/user-attachments/assets/84844ba4-8279-4ab7-84f9-58eba3e49591)

After inspecting the HTTP requests it appears it is trying to reach Meili at "meili.mydomain.com/search". If I try going there in the browser I get a 404 as well. However, if I go to "meili.mydomain.com" I get "{"status":"Meilisearch is running"}". I have tried adjusting the environment variables in docker, but it keeps trying to go to "meili.mydomain.com/search". How can I correct this?

![image](https://github.com/user-attachments/assets/8c48338e-3a62-4e01-b0e9-e607b35a5daf)

**Comment by karlomikus** [comment]
Hello,
If your meilisearch is running on the subdomain like `meili.mydomain.com`, then the .env variable should be: `MEILISEARCH_URL=meili.mydomain.com`, without any suffixes.

**Comment by gamegoofs2** [comment]
That did it, thanks! I thought I had tried that.
