### ISSUE TITLE
Salt-Rim MultiSearch broken after Meilisearch v1.11.3 upgrade.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#261]
As a followup to #253 about `Meilisearch v1.11.x - Breaking Changes`, seems `multi-search` broke for me.  I upgraded the same way I have done before, bring down all containers, delete all files on the Meilisearch volume, and bring up the containers.

Meilisearch shows a master key has been set:
```
A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
```

I make sure Bar Assistant connects:
```
Setting up Meilisearch client keys...
Clearing existing search tokens from bars...
Updating ENV...
Meilisearch setup done!
Settings for the [cocktails] index synced successfully.
Settings for the [ingredients] index synced successfully.
INFO Configuration cached successfully.
INFO Routes cached successfully.
INFO Events cached successfully.
Syncing search index...
[2024-11-19 17:17:33] production.INFO: Building search indexes
[2024-11-19 17:17:35] production.INFO: Search indexes updated
Pruning tokens with expired expires_at timestamps ............. 31.38ms DONE
```

Confirm the Meilisearch volume gets repopulated:
```
/meili_data/data.ms $ ls -R 
.:
VERSION       auth          indexes       tasks         update_files

./auth:
data.mdb  lock.mdb

./indexes:
23a9fafe-6783-4de8-be31-895bdef52dbe  7b2d7031-60df-4acc-8bab-fe616c5fda48

./indexes/23a9fafe-6783-4de8-be31-895bdef52dbe:
data.mdb  lock.mdb

./indexes/7b2d7031-60df-4acc-8bab-fe616c5fda48:
data.mdb  lock.mdb

./tasks:
data.mdb  lock.mdb

./update_files:

/meili_data/data.ms $ 
```

---

Within Salt-Rim, upon clicking `[Add Ingredient]` I get a dialog box I can't use:
![image](https://github.com/user-attachments/assets/7472a61c-02f9-4ba7-a505-4c001546ebd0)

Meilisearch logs show 403 `The provided API key is invalid`:
```
2024-11-19T16:38:58.741633Z WARN HTTP request{method=POST host="bar.[REDACTED]" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0 status_code=403 error=The provided API key is invalid.}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 403, message: "The provided API key is invalid.", error_code: "invalid_api_key", error_type: "auth", error_link: "https://docs.meilisearch.com/errors#invalid_api_key" }
```

---
I verified the KEY is set and the same in each container:

From Meilisearch (both set to same value):
```
$ echo $MEILI_MASTER_KEY
Uk2EipeE9YI6cfrEmOQ3QaiYqfATdOI1Gl4

$ echo $MEILISEARCH_KEY
Uk2EipeE9YI6cfrEmOQ3QaiYqfATdOI1Gl4
```

From Bar Assistant:
```
$ echo $MEILISEARCH_KEY
Uk2EipeE9YI6cfrEmOQ3QaiYqfATdOI1Gl4
```

From Salt-Rim:
```
$ echo $MEILISEARCH_KEY
Uk2EipeE9YI6cfrEmOQ3QaiYqfATdOI1Gl4
```

As Salt-Rim itself doesn't seem to do any logging, not sure how to troubleshoot this.

**Comment by karlomikus** [comment]
Hi,
you should try logging out, login back in and reselect the bar, this should update search token for the specific bar if it's out of sync for some reason.

**Comment by reefland** [comment]
I did try a log out/in but did not try reselect bar. That combination did the trick thank you for the prompt response.

**Comment by frank42hh** [comment]
Hi there,
sorry to reopen this issue, but I do face the exact same problem but the recommended solution didn't help here.

I recently updated to
Salt Rim: [v3.5.0]
Bar Assistant: [v4.2.0]
Meilisearch: [1.8.4]

since several versions, I can't get the reason why meilisearch only partially works.
The startup of the container is running fine, meilisearch tells me that it set its MEILI_MASTER_KEY, and I can fetch the generated search keys on the cli with via http://localhost:7700/keys with the set master key.
I see the same error message associated with the route `/multi-search` on the container log:

```
bar-assistant-meilisearch-1    | 2024-12-02T19:26:55.951349Z  INFO HTTP request{method=POST host="127.0.0.1:7700" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 status_code=403 error=The provided API key is invalid.}: meilisearch: close time.busy=683µs time.idle=1.10ms
```

but, I started my bar within an Incognito window but I still face the same problem. The multi-search doesn't work and I can't add ingredients to cocktails because of `<NOT SELECTED>` error.

The compose file is almost identical to the one in the repository, I followed the upgrade guide, and I'm not very good in docker debugging (yes, bad combo, I know), so any hints appreciated.

**Comment by reefland** [comment]
When I go back to "bars" and click "select" on my bar issue like this resolve.

**Comment by zhdenny** [comment]
All I ever do is delete the Meilisearch appdata folder before any Meilisearch update/upgrade and it works every time

**Comment by karlomikus** [comment]
If above steps don't help, usually this should work.

- Delete meilisearch container with any volumes attached to meilisearch container, for example: `docker compose down -v meilisearch`
- Create a fresh meilisearch container: `docker compose up meilisearch -d`
- Restart the bar-assistant container: `docker compose restart bar-assistant`. This should do all the required setup.
- Logout in your browser, sign back in and reselect your bar

Meilisearch made client key handling a bit annoying to deal with, but some improvement can be made in api/client.

**Comment by zhdenny** [comment]
> Well, this - for some reason - removed all my data. I'm going to check out now how to restore them from my backups... _meh_
> 
> Update: While it was a real adrenaline shot seeing that all data was gone and the system back on factory defaults, after importing my latest "full-backup" export (which could use a restore howto as well as for import-recipes) by manually unzipping it in ~/cocktails/storage/bar-assistant, it now seems that the bar is restored and for some funny reason the /multi-search target does work again now.
> 
> Only question left now is how to reset the PWA on mobile devices, since I had to clear my browser cache and relogin to get it working.

For the record, Meilisearch doesn't hold any of your actual bar data. Deleting everything related to Meilisearch shouldn't harm your bar data. Glad you got backups you could restore though 😊

**Comment by frank42hh** [comment]
> For the record, Meilisearch doesn't hold any of your actual bar data. Deleting everything related to Meilisearch shouldn't harm your bar data. Glad you got backups you could restore though 😊

That's right, I assumed that, but it seems that `docker compose up meilisearch -d` removed all volumes and not only the meilisearch volume.

**Comment by karlomikus** [comment]
I'm sorry, my bad, I have it defined as external volume so it looks like [that one gets skipped](https://docs.docker.com/reference/cli/docker/compose/down/).

Either way, check if the newest bugfix version helps with search issues.
