### ISSUE TITLE
Share - Copy to Markdown. Special Characters

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#268]
Find a cocktail which uses any special characters in the description or instructions or wherever.
Go to Share --> Copy to Markdown. Paste the result.

The special characters are not copied/processed correctly.

For example:
`Milk & Honey` gets copied as `Milk &amp; Honey`
`Please Don't Tell` gets copied as `Please Don&#039;t Tell`

**Comment by karlomikus** [comment]
Should be fixed in latest api release, thanks!
