### ISSUE TITLE
[Feature Request] Setting to Stop pulling/scraping for Drinks/Ingredients 

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#27]
Since this is now fairly stable, I have begun importing my own Ingredients/Cocktails manually by-hand in addition to editing a few that already existed. It took a long time 8-10 hours). I don't want to lose or impact that work.

I no longer want SaltRim/BarAssistant to edit or add to my ingredients/cocktails. Can this be done?

I do not mind sharing what I've done if you want. Added an additional 150 or so cocktails and many ingredients. All are from respected bartenders in Industry.

Thanks!
(This app is amazing, I like it a lot)

**Comment by karlomikus** [comment]
Hello,

This is handled by BA, it imports default cocktails/ingredients only if the database doesn't exists (by running `php artisan bar:open`). If you have correctly mapped docker volumes you will not lose any data.

I also have my personal "production" instance with a lot of custom recipes on which I test new features :D

Anyways, doing backups is usually a good practice, and I recently [started adding some information about backups](https://github.com/karlomikus/bar-assistant#database-file-backup) to BA repository.

Thanks for contributing!

**Comment by zhdenny** [comment]
Ahhh! Thank you! And yes, I most definitely maintain a backup of my appdata in case something happens. Wonderful
