### ISSUE TITLE
Salt-Rim unable to connect to milisearch.

### ISSUE THREAD

**Issue by reefland** [karlomikus/vue-salt-rim#274]
(Happy Holidays, hope all is going well... thank you for your work on this).

Salt Rim: v3.6.0
Bar Assistant: v4.2.4
Meilisearch: 1.11.3

If I understand your recent changes regarding meiliseach keys being handled via API, I shouldn't need the ENV variables defined anymore such as `MEILISEARCH_API_KEY_UID` or `MEILISEARCH_API_KEY` right?  I removed these.

I have an ENV VAR set as:
`MEILISEARCH_HOST: http://bar-assistant-search.bar-assistant.svc.cluster.local:7700`

Bar Assistant Server seems to be able to connect fine, as it logged this:
```
INFO Configuration cache cleared successfully.
Setting up bar search tokens...
Skipping Meilisearch setup. Key did not change.
Settings for the [cocktails] index synced successfully.
Settings for the [ingredients] index synced successfully.
INFO Configuration cached successfully.
INFO Routes cached successfully.
INFO Events cached successfully.
Syncing search index...
[2024-12-17 19:04:51] production.INFO: Building search indexes
[2024-12-17 19:04:52] production.INFO: Search indexes updated
Pruning tokens with expired expires_at timestamps ............. 25.00ms DONE
```

I assume to determine that `Key did not change` it connected successfully Meilisearch to determine that.

In Milisearch Logs, I can see connections such as:
```
2024-12-20T20:46:54.878418Z INFO HTTP request{method=GET host="bar-assistant-search.bar-assistant.svc.cluster.local:7700" route=/version query_parameters= user_agent=Meilisearch Laravel Scout (v10.11.9);Meilisearch PHP (v1.11.0) status_code=200}: meilisearch: close time.busy=81.9µs time.idle=128µs
```

However, on Salt-Rim Shelf it tells me `Unable to connect to the Meilisearch server at "http://bar-assistant-search.bar-assistant.svc.cluster.local:7700". Some features will be missing. `

* Being that bar-assistant doesn't do any logging, I'm not sure how to troubleshoot this when the ENV VAR is working for Bar Assistant Server.

The hostname `bar-assistant-search.bar-assistant.svc.cluster.local` is an internal name which only works on the server side of the reverse proxy (Traefik).  Salt-Rim should be able to access this fine, just like Bar Assistant can.  However, client web browsers can not resolve this name. But it's not clear if that what's happening.

**Comment by karlomikus** [comment]
API can communicate with meilisearch via whatever internal network you have set up, but salt-rim needs a meilisearch URL that you can resolve from your browser.

If you set MEILISEARCH_URL env variable in salt-rim it will [prioritize that url](https://github.com/karlomikus/vue-salt-rim/blob/develop/src/AppState.js#L32), otherwise it will pull meilisearch url from the API.

So my advice is that you set `MEILISEARCH_URL` env variable on salt-rim container to the URL you use that you can resolve from your browser.

Happy holidays!

**Comment by reefland** [comment]
That makes sense.  I used an external URL originally, removed it when clean up VARs. I did try and put that back before posting this.  But clear cache / refresh didn't help. This time I did the logoff, login and select bar and salt-rim picked up the change.  Thanks again, closing issue.
