### ISSUE TITLE
Bulk Edit/Remove/Create/Apply Tags

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#33]
Since it seems Tags are/will be used extensively, it would be wonderful if there were a method to Edit/Remove/Create/Apply tags in a more robust fashion.

Currently, it is a bit of a chore to add/remove/edit a specific tag to 20-50 drinks

**Comment by karlomikus** [comment]
There is now a basic crud management for tags available in salt rim.
Any other complex actions related to tags are currently out of scope for this project. But, if you know SQL you can work directly on the database to do the changes you want.

Thanks!

**Comment by zhdenny** [comment]
Yay! Thanks!
