### ISSUE TITLE
[Feature Request] Disable user registration

### ISSUE THREAD

**Issue by FonduemangVI** [karlomikus/vue-salt-rim#35]
Hi Loving the project so far. Could we get the option to disable new user registration. I am wanting to do this so I can put Salt Rim behind a reverse Proxy

**Comment by karlomikus** [comment]
Hi,
you can do that by setting ENV variable `ALLOW_REGISTRATION=false` in Bar Assistant.
This will disable `/register` endpoint. I will add note about that in Readme file.

Thanks!

**Comment by FonduemangVI** [comment]
Ah right thank you very much
