### ISSUE TITLE
Add to "Awesome-SelfHosted" Repository 

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#39]
This is an awesome self-hosted app. I'd recommend getting it added to the long list of Self-Hosted apps people reference here. Maybe BarTender or SaltRim, don't know which.
https://github.com/awesome-selfhosted/awesome-selfhosted

**Comment by karlomikus** [comment]
Hi,
I already opened a pull request and it's approved, only waiting for the merge. :D

https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3465

Thanks!
