### ISSUE TITLE
[Request] Favorites and Shopping LIst

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#40]
Can you make "Favorites" and "Shopping List" be separate pages outside of the "Shelf" page? I currently have over 136 favorite cocktails and I also maintain a shopping list. The "Shelf" page has become gigantic haha and it is a little painful to reach my shopping list all the way at the bottom of that page.

Thank you for your consideration on this.

**Comment by karlomikus** [comment]
Dashboard is reworked in v1.3 to make more sense, and shopping list now has its own page.

Thanks!
