### ISSUE TITLE
Safe to Delete Bot User?

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#46]
Just a general question.....I have this User listed "BAR ASSISTANT BOT" which I did not create. Is it safe to delete? Is it something required/important and I must keep?

![2023-01-27_10-38-19](https://user-images.githubusercontent.com/26662131/215126522-80556745-46b8-49b8-b3e4-dc231d8b67e1.png)

**Comment by karlomikus** [comment]
You can't delete this user currently. This user is assigned to default cocktails imported when the app starts. This is leftover from the early app versions and I will make a migration to delete it automatically in future.
