### ISSUE TITLE
Mobile Web View Include Glass/Method/ABV

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#47]
This is more a request....but can the Mobile Web View mode also include the Glass Type, Method, and ABV when viewing a cocktail? Screenshots showing the Mobile View vs The Desktop View. Thanks

![Screenshot_20230127-105119](https://user-images.githubusercontent.com/26662131/215130080-7e926dfa-083e-405b-aeee-2dc5fecdf0c3.png)

![2023-01-27 10 53 54 saltrim chickendance party 77e83119228e](https://user-images.githubusercontent.com/26662131/215130118-d940463e-4f93-4e81-b2e4-126ea56f277b.png)

**Comment by karlomikus** [comment]
This is related to PWA not refreshing the cache when the app changes, I'll fix this in next version.

Currently you need to delete the site cache of your app instance.

**Comment by zhdenny** [comment]
Oh yay! You're right. Clearing cache worked
