### ISSUE TITLE
Reorder Ingredients in Cocktail Not Working

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#48]
Now that the first ingredient in a Cocktail is considered the "Main Ingredient", I want to re-order the ingredients in some of my cocktails.

In a Desktop Web Browser, I go to edit a cocktail and try to Drag and Drop to re-arrange the cocktail ingredients. Then click Save. This change does not seem to save though. I even tried to clear my browser cache to make sure it wasn't a cache problem.

**Comment by karlomikus** [comment]
Can you write what browser are you using. Is this not working only on desktop?

**Comment by zhdenny** [comment]
These are the browsers I've tried. And just to be sure, I clear cache after I save the cocktail changes to make sure I'm viewing the most up to date version of the website and not some cached version.

Desktop (Vivaldi Browser)
Desktop (Microsoft Edge Browser)
Android Mobile (Vivaldi Browser)
Android Mobile (Samsung Internet Browser)
