### ISSUE TITLE
Bug - Show More Results Button

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#51]
Steps to reproduce Bug:

1. Click Cocktails
2. Scroll all the way down
3. Click the "Show more results" button
4. Scroll all the way down again
5. I have more cocktails to display but there is no "Show more results" button to display them. I've only hit the "S" cocktails at this point.

Verified same results on two different Web Browsers (Chromium-based and Edge) and Mobile WebView

**Comment by zhdenny** [comment]
I checked for errors in Console.....nothing stood out. I just cannot scroll beyond "Sex On The Beach" cocktail.

![2023-02-07_16-13-24](https://user-images.githubusercontent.com/26662131/217366914-292296f3-0e90-4ed8-9f50-0c68f1441d12.png)


![vivaldi_2023-02-07_16-09-19](https://user-images.githubusercontent.com/26662131/217367093-f0964e5c-ea2c-4810-9f0f-ca09b2515959.png)

**Comment by karlomikus** [comment]
I'll do some more digging but everything looks fine. Maybe meilisearch got out of sync, try to restart the bar-assistant container and see if it's fixed.

**Comment by zhdenny** [comment]
I tried recreating all containers (keeping my appdata of course). This also made me realize I was running meilisearch container with the ":latest" tag....which was bad since Meilisearch currently doesn't auto-update your database to new version. I've since pinned my meilisearch instance to the version I used when I first started using Bar-Assistant / SaltRim.

**Comment by karlomikus** [comment]
Hmmm, interesting. I also updated my meilisearch accidentally and rolled back but I didn't have any errors.

You could try to run search refresh with clear indexes option:

```bash
docker compose exec bar-assistant php artisan bar:refresh-search -c
```

**Comment by zhdenny** [comment]
just tried

```
docker compose exec bar-assistant php artisan bar:refresh-search -c
```

Result:
```
Flushing site search, cocktails and ingredients index...
Updating search index settings...
Syncing cocktails and ingredients to meilisearch...
```

It did not fix the problem though. Boo

**Comment by karlomikus** [comment]
Can you check your network tab to see if there are any errors when you are browsing the cocktails page and clicking show more.

Also it's possible that your meilisearch api keys got mixed up when accidentally updating the image. Try running the following (Note that this method does not output anything):

``` bash
docker compose exec bar-assistant php artisan bar:refresh-user-search-keys
```

After running the command clear the cache and check if it's working.

**Comment by zhdenny** [comment]
Network Tab in F12 console does not show errors.

Tried the following command and clearing cache/data on browser. I still cannot get the "Show More Results" button to appear after clicking it once and scrolling all the way down again.

```
docker compose exec bar-assistant php artisan bar:refresh-user-search-keys
```

I do now see an error in F12 console on Chrome browser....but I do not see any error on Microsoft Edge Browser. My issue occurs across any browser though including Microsoft Edge.
Chrome F12 console Error message below (edited out my domain):

```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://saltrim.domain.com/') with script ('https://saltrim.domain.com/sw.js'): An unknown error occurred when fetching the script.
```

**Comment by zhdenny** [comment]
**Update:**
I successfully updated my Meilisearch instance to the latest version (`v1.0.1`). I followed your instructions. After updating, I had to run `docker compose exec bar-assistant php artisan bar:refresh-user-search-keys` in order to see any cocktails/ingredients. So now I am fully updated on Meilisearch. Might be worth mentioning users may need to run that command after updating.

Unfortunately, this did not solve my issue. I am still unable to get the "Show More Results" button to appear after clicking it once and scrolling all the way down again. It only appears the first time.

**I do notice something interesting. My issue only occurs with viewing Cocktails**. Viewing ingredients, everything works correctly. When viewing Ingredients, I scroll down and see the "Show More Results" button and scroll down again and see the "Show More Results" button again and can continue to scroll down.

So this is interesting that my issue is exclusive to viewing Cocktails

**Comment by karlomikus** [comment]
When you search for the cocktails that are missing from the page, do they show on the page?

**Comment by zhdenny** [comment]
Yes. All of my cocktails still exist and are viewable. This is exclusively a scrolling issue with viewing a list of cocktails.... It doesn't matter which cocktails

To prove that, I can sort the cocktails in reverse-alphabetical order and see all my drinks in the list beginning with the letter Z instead of A. I scroll all the way down, press the "Show More Results" button, then scroll all the way down again, the "Show More Results" button doesn't appear even though I have more cocktails to show.... I've only reached to somewhere around cocktails starting with the letter C.

The same issue occurs when viewing a list of favorites. If you have enough favorites to scroll enough times.... Say Over 100 or so.

**Comment by zhdenny** [comment]
And if this helps, I've made a video to demonstrate the issue is specific to scrolling and is independent on which cocktails are being scrolled through.

[https://youtu.be/HUdMuusjCfU](url)

**Comment by karlomikus** [comment]
I managed to recreate it locally, I'm working on a fix

**Comment by zhdenny** [comment]
OMG yay!!! You're awesome

**Comment by zhdenny** [comment]
Issue is officially resolved! Thanks a bunch for hanging in there with me to solve this
