### ISSUE TITLE
Initial setup w/docker-compose --initial db-entries?

### ISSUE THREAD

**Issue by cmuc24** [karlomikus/vue-salt-rim#54]
https://github.com/bar-assistant/docker/blob/master/docker-compose.yml

- First run, without any issues, perfect. 
- Register new User, login, yes allright.
- Empty database, hmm.. 
    - try to scrape / add from url, from your demo-instance ... failed
    - try to scrape with one of your scraper, yes fine, but failed to save ingredients and some more.
    - try to create ingredient-categories, glasses, ingredients... failed
    - Searched for an Import/Export of DB in Settings, there is no way via UI. or may i missed some steps?
I saw the oneliner for DB Backup, but what should i do with a backup of an empty DB?

My suggest:  #MenuSettings #Import/Export DB 
User can export DB from Demo-Instance, and... yes, import to own instance. But, yes a full DB after install/up & running should also make happy users :-) 

Off-Topic
I see your fabulous system in a totally different use-case i work on around since months, in short: 
Just imagine repositories and container ('selfhosted-apps') as entities, doesnt matter if u r running or not. instead recipes, an intelligent app catalog, with some social components and not only stupid copies of Readme's. yea. Its not only a project 'just for fun and freedom' so, If you like the idea or parts of, get ready for more :)

**Comment by zhdenny** [comment]
If database is empty that would indicate something wrong with Meilsearch connection I think. Look at docker logs for each related container 

When working right, you should login to a database full of base cocktails and ingredients

**Comment by karlomikus** [comment]
Your database is empty, I'm guessing its something related to the meilisearch like @zhdenny wrote, or you configured your volumes incorrectly. You should checkout your logs for more info about the errors.

**Comment by karlomikus** [comment]
New docker improvements are now available as a release candidate.
I welcome you to try the new setup, you can [find the guide here](https://bar-assistant.github.io/docs/setup/).

If you are still having problems please open a new issue.
