### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#57]
It would be nice to have a Dark Mode toggle. Makes things so much easier on the eyes. Thanks

**Comment by daniel-simpson** [comment]
Just as an add on for this: as much as I'd love a dark theme, it would be especially amazing if you could even just add anempty CSS file in the assets folder to allow custom user styling.

Something like an empty `assets/userstyles.css` would be perfect, as it could be overridden using a docker file/folder volume mount. 🙏
