### ISSUE TITLE
Cocktails/Ingredients not displaying

### ISSUE THREAD

**Issue by h3g0rt** [karlomikus/vue-salt-rim#58]
I followed the instructions from here https://bar-assistant.github.io/docs/setup/ (Quick setup with Docker compose) 
Architecture: Raspberry Pi 3, ARM64

Everything seems to be working fine, no errors when executing "docker compose logs bar-assistant"
At the "shelf" page all cocktails are displayed, can be viewed and edited but on "cocktails" and "ingredients" page the overview is not loading, it just shows a blank page and throws an error:

MeiliSearchApiError: Index `cocktails` not found.

![shelf](https://user-images.githubusercontent.com/82532268/222220262-01290211-8bf0-45fb-9f98-364b8b556e28.jpeg)
![cocktails](https://user-images.githubusercontent.com/82532268/222220259-018db9ba-a5f0-41e9-bc60-978d77f23564.jpeg)
![error](https://user-images.githubusercontent.com/82532268/222220255-95770338-d71b-4c2a-9d65-d3388893c358.jpeg)

**Comment by zhdenny** [comment]
So it looks like a Meilisearch problem. What does "docker compose logs meilisearch" say?

**Comment by h3g0rt** [comment]
Thanks for your reply! 
Here you go: [_bar-assistant-meilisearch-1_logs.txt](https://github.com/karlomikus/vue-salt-rim/files/10865128/_bar-assistant-meilisearch-1_logs.txt)

**Comment by karlomikus** [comment]
Try running the following 2 commands.

```
$ docker compose exec bar-assistant php artisan bar:refresh-search
$ docker compose exec bar-assistant php artisan bar:refresh-user-search-keys
```

This will sync your Meilisearch with the Bar Assistant data

**Comment by h3g0rt** [comment]
Ran without errors, but unfortunately it didnt help, same error.

**Comment by karlomikus** [comment]
Thats weird, since it looks like Meilisearch is functioning properly.
Try this: logout from the salt rim, then clear the browser cache for salt rim.
This should reset old Meilisearch api key that is maybe cached in the browser.

**Comment by h3g0rt** [comment]
Ok, did that and tested it with other Browsers as well. Same error unfortunately.

**Comment by h3g0rt** [comment]
After digging a bit in the Chrome Dev Console I saw this error: 

http://192.168.0.215:3000/search/indexes/cocktails/search
{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}

**Comment by karlomikus** [comment]
That error is weird since you can see the Authorization header in the request.

Try again, with the "fresh" installation.

```
$ docker compose down -v
$ docker compose up -d
```

**Comment by h3g0rt** [comment]
Indeed, this is very strange. Did that at least a dozen of times with different settings, but the error stays the same. 

![error](https://user-images.githubusercontent.com/82532268/222562827-67f88b10-e85d-48ad-bd05-199572635059.jpg)

**Comment by zhdenny** [comment]
Can you give your docker compose yml. There's gotta be something going on here

**Comment by h3g0rt** [comment]
Oh, sorry my bad, there was something lost when I copied it into my reply. 
Tried it now again with exactly the one from the Setup Docs, same error. :/

**Comment by zhdenny** [comment]
Ok, get a shell into your webserver image and run these ping commands. Do you get a ping response for each?
 ```
docker exec -it webserver /bin/sh
ping bar-assistant:3000
ping meilisearch:7700
ping salt-rim:8080
 ```
 
 Report results of the commands.

**Comment by h3g0rt** [comment]
Seems to be fine: 

docker exec -it bar-assistant-webserver-1 /bin/sh
/ # ping bar-assistant:3000
PING bar-assistant:3000 (172.22.0.5): 56 data bytes
64 bytes from 172.22.0.5: seq=0 ttl=64 time=0.469 ms
64 bytes from 172.22.0.5: seq=1 ttl=64 time=0.390 ms
^C
--- bar-assistant:3000 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.386/0.411/0.469 ms
/ # ping meilisearch:7700
PING meilisearch:7700 (172.22.0.4): 56 data bytes
64 bytes from 172.22.0.4: seq=0 ttl=64 time=0.657 ms
64 bytes from 172.22.0.4: seq=1 ttl=64 time=0.389 ms
^C
--- meilisearch:7700 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.381/0.441/0.657 ms
/ # ping salt-rim:8080
PING salt-rim:8080 (172.22.0.6): 56 data bytes
64 bytes from 172.22.0.6: seq=0 ttl=64 time=0.887 ms
64 bytes from 172.22.0.6: seq=1 ttl=64 time=0.390 ms
^C
--- salt-rim:8080 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.387/0.513/0.887 ms

**Comment by h3g0rt** [comment]
Testet it now on an AMD64 machine and all is fine, working perfectly. Seems to be a problem with the ARM64 version.
I did remove everything from the RaspberryPI and pulled the images again. Everything spins up nicely but I still get the Error.

**Comment by karlomikus** [comment]
I have RPi3, I'll do some testing

**Comment by karlomikus** [comment]
Meilisearch runs out of memory, related to https://github.com/meilisearch/meilisearch/issues/3488

**Comment by h3g0rt** [comment]
Ah nice, thank you very much for your effort! I tried the newest nightly image of Meilisearch and it seems to work just fine now. :)
