### ISSUE TITLE
[Feature Request] Possibility to remove login

### ISSUE THREAD

**Issue by IC3P3** [karlomikus/vue-salt-rim#61]
An account is not necessarily needed. For example when I want to access Salt Rim in my private network, there is noone that shouldn't access the web interface in my network. Furthermore for external use (behind a revese proxy) I use Authelia which could replace this account system.
This could possibly a variable in the compose file which you could switch between true and false for accounts to be enabled or disabled.

**Comment by karlomikus** [comment]
Available via `DISABLE_LOGIN=true`

**Comment by Sagelt** [comment]
Is there any additional documentation on how to use this environment variable? I've set DISABLE_LOGIN=true on both barassisstant and salt-rim in my docker compose, but am still getting the login/register page.

Full docker compose for reference:

`version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.4
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - meilisearch_data:/meili_data

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  bar-assistant:
    image: barassistant/server:v3
    depends_on:
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - DISABLE_LOGIN=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v2
    depends_on:
      bar-assistant:
        condition: service_healthy
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - DEFAULT_LOCALE=en-US
      - DISABLE_LOGIN=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      bar-assistant:
        condition: service_healthy
      salt-rim:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  bar_data:
  meilisearch_data:
`

**Comment by karlomikus** [comment]
This feature was removed starting with v3 since initial data now needs to be created by specific user.
You can still disabled registrations via `ALLOW_REGISTRATION=false` on bar-assistant container.

**Comment by Sagelt** [comment]
Ah, okay. So there's not currently a way to enable a non-logged-in view? Similar to folks here and in #78 I have a local install only accessible to my home network and I'd like anyone on my network to be able to view my install as a kind of menu without having to create an account.

**Comment by zhdenny** [comment]
When guests are over, I have a tablet at my bar which is logged in and wait for them to use
