### ISSUE TITLE
Users should not be able to add ingredients to the shelf

### ISSUE THREAD

**Issue by mrdmiller2** [karlomikus/vue-salt-rim#81]
This is great, and I'm planning on using it for my home bar.. but a "user" should never be able to modify the contents of the shelf.  That should be reserved for admins.  As it stands right now, there is little difference between a user and a admin other than the admin can add users.

**Comment by zhdenny** [comment]
There are many differences between Non-Admin (User) and Admin. I just confirmed. I think you should check again. There are many actions which will receive permission errors if a user attempts to do them.

1. Users cannot modify/create/delete Ingredients
2. Users cannot modify/create/delete cocktails
3. Users cannot/modify/create/delete glasses or categories or tags.
4. Each user controls their own Shelf though as you already described. And by control all they can do is check/uncheck what they have or do not have available. This is rather desirable in my opinion as it allows each user to determine which drinks they are or are not capable of making based on their own ingredient availability. But a user is NOT able to modify/create/delete any ingredients.

Hope this helps

**Comment by karlomikus** [comment]
Pretty much what @zhdenny said. Each user has his own shelf and can modify it as he pleases.

Admins can also modify any cocktail/ingredient, while users can modify only cocktails/ingredients that they created.

**Comment by mrdmiller2** [comment]
I see.. so is there a way to have a "read only" user/model?.. because what I would love for others to see is just the ingredients I have on hand and the cocktails I can make with them, (and maybe submit a cocktail recipe of their own but otherwise they can look all day long, but not alter anything I've setup?

Let me paint the scenario.  I have guests coming over and I offer them a drink (which inevitably leads to the question "what do you have/what can I have).  As it stands now, i have to create either a "guest" account or let them create their own accounts.. (making a guest account isn't bad.. no real issue, but then that means everyone is logging in to the same account and when they start "experimenting, adding things to their shelves and other things, it messes up the experience for everyone else using that same account). If I let them create their own accounts, now I have to "teach" my guests how to create an account/login, etc.. before even getting to the drink options... at that point my wife will just offer them water to bypass the whole issue and after a meal I'm going to be told by her "too complicated")

Hence why its good to either have a read only user so you can make a generic "guest" account that is read only.. And if you have other more tech savvy/drink savvy people coming over then you can make other accounts so they can "customize" their experience.

**Comment by karlomikus** [comment]
This is something that will come in the future. Probably in a form of user collections that can be shared, but I haven't given this too much thought. Nevertheless, I think you described the only currently available solutions.

Thanks for the feedback
