### ISSUE TITLE
Lost Ingredients...

### ISSUE THREAD

**Issue by mrdmiller2** [karlomikus/vue-salt-rim#89]
I encountered a very odd situation where I've added/modified an ingredient.. and it appeared to be successful.. And after some time, I went back I noticed that if I display the ingredient list or I search for it.. it shows up, but when I try to display it, I get a lost record error.  

After checking the database, that ingredient doesn't actually exist in the database.. which means there is a disconnect between the database and the meillisearch index.... 

<img width="630" alt="Screenshot 2023-06-16 at 01 23 18" src="https://github.com/karlomikus/vue-salt-rim/assets/23031384/ae6fe62b-af50-4b52-9d5f-e38a4c997b23">

**Comment by karlomikus** [comment]
This could sometimes happen between instance updates or some other glitch and it's not easy to debug. If you can reproduce the issue then please post the steps.

To fix leftover ingredients you can run the following command:

``` bash
docker compose exec bar-assistant php artisan bar:refresh-search --clear
```

**Comment by AGJSpiegelenberg** [comment]
I have the same issue. When creating a new user everething is fine but for existing users the list is empty. 
It looks the users Search API key does not work.

**Comment by mrdmiller2** [comment]
So this keeps happening randomly...   even with ingredients that are "old" and previously working.. So there is something causing a disconnect/break between the DB and the search engine.

I don't really have any steps to reproduce it other than adding/editing other ingredients.  If you want my "bar" accessible externally so I could provide access to it so you can see what's going on..
