### ISSUE TITLE
Feature Request - Import multiple cocktails via JSON

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#93]
Can the new Export/Import via JSON support multiple Cocktails?

Or at a minimum, can the new Import cocktail via JSON support a JSON dump of multiple cocktails?

I understand a full database import would wipe current database.....I'm looking for a way to export/import regularly 5-15 cocktails without wiping out someone's current database.

**Comment by karlomikus** [comment]
Until some other method is implemented, this is now possible by sharing and importing cocktail collections.
