### ISSUE TITLE
Navigation Issues when browsing with filters

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#99]
This is very closely related to this recently resolved bug report
https://github.com/karlomikus/vue-salt-rim/issues/87

Everything is working great with Navigation now except for one minor detail. And I do not know if you can or will fix this.

**Steps to reproduce:**
1. Use a cocktail filter which yields enough results to require the "show more" button to appear at the bottom of the scrolling page.
2. Scroll all the way down. Press the "show more" button.
3. Select a cocktail which appears after the "show more" button.
4. Navigate back. What do you see?

I would expect to be taken back to the exact scroll position I was at before...but instead the user is taken to bottom of the 1st page of results with the "show more" button. In order for the user to return to where they were they must now press the "show more" button again and scroll down some more.

This problem gets more troublesome when a cocktail filter yields multiple pages worth of results.

**Comment by karlomikus** [comment]
Seems like instant-search does not keep track of pagination so I do not think this is an easy fix.

Meilisearch/instant-search is not really suited for listing all data and using it in a way that is currently implemented. I'm in the process of moving cocktails list data source from Meilisearch to normal API calls, which should hopefully improve routing.
